# Generated by Django 4.1.4 on 2023-09-15 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_usermembership_c_id_alter_businesslogs_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="principal_amount_per_month",
            field=models.CharField(default="10", max_length=250),
        ),
        migrations.AddField(
            model_name="usermembership",
            name="price",
            field=models.CharField(default="0", max_length=250),
        ),
        migrations.AddField(
            model_name="usermembership",
            name="principal_amount",
            field=models.CharField(default="0", max_length=250),
        ),
        migrations.AlterField(
            model_name="businesslogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 17509),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="changesponserlogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 18483),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="farmingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 19511),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="levelincome",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 21487),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="newsmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 20487),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ptransfer",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 23484),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="rewardlogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 16, 49, 34, 24493),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="stakingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 20487),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="status_activity",
            name="time",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 22410),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 21487),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 16439),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 16439),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usercofounderclub",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 25508),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 19511),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userrank",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 25508),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 23484),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userrewards",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 16, 49, 34, 24493),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userrewards",
            name="next_date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 16, 49, 34, 24493),
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="userstaking",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 19511),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userwithdrawls",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 19, 34, 22410),
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="Principallogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        default=datetime.datetime(2023, 9, 15, 11, 19, 34, 19511),
                        max_length=200,
                    ),
                ),
                ("status", models.CharField(default="1", max_length=100)),
                ("amount", models.CharField(default="0", max_length=200)),
                (
                    "plan_id",
                    models.ForeignKey(
                        db_column="plan_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usermembership",
                    ),
                ),
            ],
            options={
                "db_table": "principallogs",
            },
        ),
    ]
