# Generated by Django 4.1.4 on 2023-09-15 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_membership_principal_amount_per_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="principal_amount",
            field=models.CharField(default="100", max_length=250),
        ),
        migrations.AlterField(
            model_name="businesslogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 838211),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="changesponserlogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 838211),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="farmingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 839214),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="levelincome",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 843217),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="newsmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 841217),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="principallogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 840211),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="ptransfer",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 845217),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="rewardlogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 16, 54, 21, 847213),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="stakingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 841217),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="status_activity",
            name="time",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 844217),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 843217),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 836215),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 836215),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usercofounderclub",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 847213),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 839214),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userrank",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 848213),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 845217),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userrewards",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 16, 54, 21, 846215),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userrewards",
            name="next_date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 16, 54, 21, 847213),
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="userstaking",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 840211),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userwithdrawls",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 15, 11, 24, 21, 844217),
                max_length=200,
            ),
        ),
    ]
